### ISSUE TITLE
Error: There was a problem connecting to the payment gateway.

### ISSUE THREAD

**Issue by korynorthrop** [affinipay/affinipay-woocommerce#1] opened 2016-01-20 18:03 UTC
I'm trying to use this plug-in for a client's website, but whenever I try to run a transaction in Test mode I get the following error, "Error: There was a problem connecting to the payment gateway." Do you have any suggestions on where to begin debugging? I have copied over the client's API keys/tokens from their LawPay account.

**Comment by cbrummer** [comment] 2016-07-08 15:09
We are having the exact same issue. The client upgraded their account in order to do this. Is there any word on when this will be fixed?

**Comment by udev** [comment] 2017-03-24 16:00
@korynorthrop and @cbrummer 

Thank you for reporting on this issue. There is a pull request incoming that might resolve the reported issue. If you have additional information in the form of logs or additional error messages or screenshots please feel free to share that information here.

**Comment by udev** [comment] 2017-03-27 19:57
With PR #9 in we're unable to reproduce this issue. Please open a new issue if the problem persists.

**Closed as completed** 2017-03-27 19:57 UTC
